"""
tests/test_color_extractor.py — Unit Tests for utils/color_extractor.py
========================================================================

Color extraction tests work on real (but synthetic) images generated by Pillow.
We create simple solid-colour and gradient images in memory rather than loading
files from disk. This makes the tests:
    - Fast (no disk I/O)
    - Deterministic (same image every run)
    - Self-contained (no test fixture files to manage)

Key things we verify:
    - The palette output format (HEX strings, correct count)
    - The histogram output format (48 floats, correct range)
    - Correctness of dominant color detection (a solid red image should give #FF...)
    - The batch processing function (process_all_pending) integrates correctly
"""

import os
import json
import pytest
from io import BytesIO
from PIL import Image

from utils.database import initialize_db, insert_images, update_download
from utils.color_extractor import (
    extract_dominant_colors,
    extract_color_histogram,
    process_all_pending,
    N_DOMINANT_COLORS,
    HISTOGRAM_BINS,
)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def save_test_image(tmp_path, filename: str,
                    color: tuple = (26, 26, 46),
                    size: tuple = (300, 300)) -> str:
    """
    Create a solid-colour PNG test image and save it to tmp_path.
    Returns the absolute path to the saved file.
    """
    img = Image.new("RGB", size, color=color)
    path = str(tmp_path / filename)
    img.save(path, format="PNG")
    return path


def save_gradient_image(tmp_path, filename: str) -> str:
    """
    Create a simple horizontal gradient from dark blue to bright orange.
    Useful for testing that the palette picks up multiple distinct colors.
    """
    width, height = 300, 300
    img = Image.new("RGB", (width, height))
    pixels = img.load()
    for x in range(width):
        t = x / (width - 1)
        r = int(26  + t * (255 - 26))
        g = int(26  + t * (140 - 26))
        b = int(46  + t * (0   - 46))
        for y in range(height):
            pixels[x, y] = (r, g, b)
    path = str(tmp_path / filename)
    img.save(path, format="PNG")
    return path


@pytest.fixture
def conn():
    connection = initialize_db(":memory:")
    yield connection
    connection.close()


# ─── Tests: extract_dominant_colors ──────────────────────────────────────────

def test_dominant_colors_returns_correct_count(tmp_path):
    """
    extract_dominant_colors() should return exactly N_DOMINANT_COLORS colors.
    """
    path = save_test_image(tmp_path, "dark.png")
    palette = extract_dominant_colors(path)
    assert len(palette) == N_DOMINANT_COLORS


def test_dominant_colors_are_valid_hex(tmp_path):
    """
    Each color in the palette should be a valid HEX string (#RRGGBB format).
    """
    path = save_test_image(tmp_path, "dark.png")
    palette = extract_dominant_colors(path)

    for color in palette:
        # Must start with #
        assert color.startswith("#"), f"{color} does not start with #"
        # Must be exactly 7 characters (#RRGGBB)
        assert len(color) == 7, f"{color} is not 7 characters"
        # Characters after # must be valid hex digits
        hex_part = color[1:]
        assert all(c in "0123456789ABCDEFabcdef" for c in hex_part), \
            f"{color} contains non-hex characters"


def test_dominant_colors_solid_red_image(tmp_path):
    """
    A solid red image should produce a palette where the dominant color
    is approximately red (#FF0000 or close to it).

    We test that the R channel is high and the G+B channels are low in
    the most dominant color.
    """
    path = save_test_image(tmp_path, "red.png", color=(220, 30, 30))
    palette = extract_dominant_colors(path)

    # Parse the most dominant color
    most_dominant = palette[0]
    r = int(most_dominant[1:3], 16)
    g = int(most_dominant[3:5], 16)
    b = int(most_dominant[5:7], 16)

    # Red channel should be significantly higher than green and blue
    # (allowing some tolerance because LAB conversion is not perfectly lossless)
    assert r > 150, f"Expected R to be high, got {r} in {most_dominant}"
    assert g < 100, f"Expected G to be low, got {g} in {most_dominant}"


def test_dominant_colors_custom_n(tmp_path):
    """
    Requesting a different number of colors should return that exact count.
    """
    path = save_test_image(tmp_path, "test.png")
    palette_3 = extract_dominant_colors(path, n_colors=3)
    palette_8 = extract_dominant_colors(path, n_colors=8)

    assert len(palette_3) == 3
    assert len(palette_8) == 8


def test_dominant_colors_gradient_has_variety(tmp_path):
    """
    A gradient image should produce colors that vary meaningfully
    rather than all being the same (which would indicate a bug).
    """
    path = save_gradient_image(tmp_path, "gradient.png")
    palette = extract_dominant_colors(path)

    # Convert all colors to RGB tuples for comparison
    rgb_values = [
        (int(c[1:3], 16), int(c[3:5], 16), int(c[5:7], 16))
        for c in palette
    ]

    # Check that not all colors are identical
    unique_colors = set(rgb_values)
    assert len(unique_colors) > 1, "All dominant colors are identical — gradient not detected"


# ─── Tests: extract_color_histogram ──────────────────────────────────────────

def test_histogram_returns_correct_length(tmp_path):
    """
    The histogram vector should have HISTOGRAM_BINS * 3 elements.
    With defaults (16 bins, 3 channels), this is 48.
    """
    path = save_test_image(tmp_path, "dark.png")
    hist = extract_color_histogram(path)

    assert len(hist) == HISTOGRAM_BINS * 3


def test_histogram_values_are_floats_in_valid_range(tmp_path):
    """
    All histogram values should be floats between 0.0 and 1.0 (inclusive).
    Values outside this range would indicate a normalization bug.
    """
    path = save_test_image(tmp_path, "dark.png")
    hist = extract_color_histogram(path)

    for i, val in enumerate(hist):
        assert isinstance(val, float), f"Value at index {i} is {type(val)}, not float"
        assert 0.0 <= val <= 1.0, f"Value {val} at index {i} is out of [0, 1] range"


def test_histogram_channels_each_sum_to_one(tmp_path):
    """
    The histogram for each channel should be normalized so it sums to 1.0.

    With HISTOGRAM_BINS = 16:
        - Indices 0–15  = L channel histogram
        - Indices 16–31 = a channel histogram
        - Indices 32–47 = b channel histogram
    """
    path = save_test_image(tmp_path, "dark.png")
    hist = extract_color_histogram(path)

    for channel_idx in range(3):
        start = channel_idx * HISTOGRAM_BINS
        end   = start + HISTOGRAM_BINS
        channel_sum = sum(hist[start:end])
        assert abs(channel_sum - 1.0) < 1e-5, \
            f"Channel {channel_idx} histogram sums to {channel_sum}, expected 1.0"


def test_histogram_custom_bins(tmp_path):
    """
    Using a custom number of bins should produce a vector of bins*3 length.
    """
    path = save_test_image(tmp_path, "dark.png")
    hist = extract_color_histogram(path, bins=8)
    assert len(hist) == 8 * 3


def test_histogram_dark_image_has_low_l_channel(tmp_path):
    """
    A dark image should have most of its L (lightness) channel mass
    concentrated in the low bins (near 0 on the 0–100 scale).
    """
    path = save_test_image(tmp_path, "very_dark.png", color=(10, 10, 10))
    hist = extract_color_histogram(path)

    # L channel occupies the first HISTOGRAM_BINS values.
    # For a very dark image, most weight should be in the first few bins.
    l_channel = hist[:HISTOGRAM_BINS]
    # Sum of the first quarter of the L bins should be high
    first_quarter_sum = sum(l_channel[: HISTOGRAM_BINS // 4])
    assert first_quarter_sum > 0.5, \
        f"Dark image should have high L-channel weight in low bins, got {first_quarter_sum}"


# ─── Tests: process_all_pending ──────────────────────────────────────────────

def test_process_all_pending_no_downloaded_images(conn):
    """
    If no images have been downloaded, process_all_pending() should report
    0 images attempted and not raise any errors.
    """
    stats = process_all_pending(conn)
    assert stats["attempted"] == 0


def test_process_all_pending_success(conn, tmp_path):
    """
    process_all_pending() should process all downloaded images and update
    the database with both dominant_colors and color_histogram.
    """
    # Insert a record and mark it as downloaded (pointing to a real test image)
    record = {
        "source": "behance",
        "keyword": "dark minimalism",
        "image_url": "https://example.com/test.jpg",
    }
    insert_images(conn, [record])

    # Create a real image file to process
    img_path = save_test_image(tmp_path, "test_img.png", color=(50, 100, 150))
    row_id   = conn.execute("SELECT id FROM images LIMIT 1").fetchone()[0]
    update_download(conn, row_id, img_path, 50000, 300, 300)

    stats = process_all_pending(conn)

    assert stats["succeeded"] == 1
    assert stats["failed"]    == 0

    # Verify database was updated correctly
    row = conn.execute("SELECT * FROM images WHERE id = ?", (row_id,)).fetchone()

    palette   = json.loads(row["dominant_colors"])
    histogram = json.loads(row["color_histogram"])

    assert isinstance(palette,   list)
    assert len(palette)   == N_DOMINANT_COLORS
    assert isinstance(histogram, list)
    assert len(histogram) == HISTOGRAM_BINS * 3


def test_process_all_pending_skips_missing_files(conn, tmp_path):
    """
    If a record's local_path points to a file that does not exist on disk,
    the function should count it as failed and continue (not crash).
    """
    record = {
        "source": "pinterest",
        "keyword": "dark minimalism",
        "image_url": "https://example.com/missing.jpg",
    }
    insert_images(conn, [record])
    row_id = conn.execute("SELECT id FROM images LIMIT 1").fetchone()[0]

    # Set a local_path to a file that does not exist
    update_download(conn, row_id, "/nonexistent/path/image.jpg", 0, 100, 100)

    stats = process_all_pending(conn)

    assert stats["failed"]    == 1
    assert stats["succeeded"] == 0


def test_process_all_pending_is_idempotent(conn, tmp_path):
    """
    Running process_all_pending() twice should not re-process images that
    were already processed in the first run.
    """
    record = {
        "source": "behance",
        "keyword": "dark minimalism",
        "image_url": "https://example.com/test2.jpg",
    }
    insert_images(conn, [record])
    img_path = save_test_image(tmp_path, "test2.png")
    row_id   = conn.execute("SELECT id FROM images LIMIT 1").fetchone()[0]
    update_download(conn, row_id, img_path, 50000, 300, 300)

    stats_first  = process_all_pending(conn)
    stats_second = process_all_pending(conn)

    assert stats_first["succeeded"]  == 1
    # Second run should have nothing to process
    assert stats_second["attempted"] == 0
